import { Tag } from "./app/models/Tag";
import { Ticket } from "./app/models/Ticket";

export const sample_tickets: Ticket[] = [
  {
    id:'1',
    avio_prevozinik: 'FlyDubai',
    polazna_lokacija: 'Belgrade',
    odredisna_lokacija: 'Dubai',
    vreme_trajanja_leta_sati: 5,
    vreme_trajanja_leta_minuti: 10,
    klasa: 'business',
    broj_preostalih_mesta: 10,
    cena: 470,
    tags: ['FlyDubai','Dubai', 'Belgrade'],
    favorite: true,
    imageUrl: 'assets/7.jpg',
    stars: 5,
    status: "done",
    polazni_aerodrom: 'Nikola Tesla',
    dolazni_aerodrom: 'Dubai Airport'
  },
  {
    id:'13',
    avio_prevozinik: 'AirSerbia',
    polazna_lokacija: 'Belgrade',
    odredisna_lokacija: 'Paris',
    vreme_trajanja_leta_sati: 4,
    vreme_trajanja_leta_minuti: 20,
    klasa: 'first',
    broj_preostalih_mesta: 21,
    cena: 489,
    tags: ['AirSerbia','Paris', 'Belgrade'],
    favorite: false,
    imageUrl: 'assets/1.jpg',
    stars: 5,
    status: "next",
    polazni_aerodrom: 'Nikola Tesla',
    dolazni_aerodrom: 'Paris Charles de Gaulle Airport'
  },
  {
    id:'3',
    avio_prevozinik: 'Delta',
    polazna_lokacija: 'New York',
    odredisna_lokacija: 'Belgrade',
    vreme_trajanja_leta_sati: 12,
    vreme_trajanja_leta_minuti: 55,
    klasa: 'economy',
    broj_preostalih_mesta: 25,
    cena: 700,
    tags: ['Delta','New York', 'Belgrade'],
    favorite: false,
    imageUrl: 'assets/3.jpg',
    stars: 4,
    status: "cancelled",
    polazni_aerodrom: 'John F. Kennedy',
    dolazni_aerodrom: 'Nikola Tesla'
  },
  {
    id:'5',
    avio_prevozinik: 'Wizz',
    polazna_lokacija: 'Belgrade',
    odredisna_lokacija: 'London',
    vreme_trajanja_leta_sati: 3,
    vreme_trajanja_leta_minuti: 5,
    klasa: 'economy',
    broj_preostalih_mesta: 7,
    cena: 281,
    tags: ['Wizz','London', 'Belgrade'],
    favorite: true,
    imageUrl: 'assets/2.jpg',
    stars: 4,
    status: "done",
    polazni_aerodrom: 'Nikola Tesla',
    dolazni_aerodrom: 'London Stansted'
  },
  {
    id:'8',
    avio_prevozinik: 'RyanAir',
    polazna_lokacija: 'Dublin',
    odredisna_lokacija: 'London',
    vreme_trajanja_leta_sati: 1,
    vreme_trajanja_leta_minuti: 20,
    klasa: 'first',
    broj_preostalih_mesta: 11,
    cena: 76,
    tags: ['RyanAir','London', 'Dublin'],
    favorite: true,
    imageUrl: 'assets/2.jpg',
    stars: 2,
    status: "next",
    polazni_aerodrom: 'Dublin Airport',
    dolazni_aerodrom: 'London Luton'
  },
  {
    id:'7',
    avio_prevozinik: 'RyanAir',
    polazna_lokacija: 'London',
    odredisna_lokacija: 'Dublin',
    vreme_trajanja_leta_sati: 1,
    vreme_trajanja_leta_minuti: 55,
    klasa: 'economy',
    broj_preostalih_mesta: 10,
    cena: 40,
    tags: ['RyanAir','London', 'Dublin'],
    favorite: false,
    imageUrl: 'assets/6.jpg',
    stars: 5,
    status: "cancelled",
    polazni_aerodrom: 'London Luton',
    dolazni_aerodrom: 'Dublin Airport'
  },
  {
    id:'4',
    avio_prevozinik: 'Delta',
    polazna_lokacija: 'Belgrade',
    odredisna_lokacija: 'New York',
    vreme_trajanja_leta_sati: 13,
    vreme_trajanja_leta_minuti: 45,
    klasa: 'first',
    broj_preostalih_mesta: 25,
    cena: 1000,
    tags: ['Delta','New York', 'Belgrade'],
    favorite: true,
    imageUrl: 'assets/9.jpg',
    stars: 2,
    status: "done",
    polazni_aerodrom: 'Nikola Tesla',
    dolazni_aerodrom: 'John F. Kennedy'
  },
  {
    id:'10',
    avio_prevozinik: 'easyJat',
    polazna_lokacija: 'London',
    odredisna_lokacija: 'Dubrovnik',
    vreme_trajanja_leta_sati: 2,
    vreme_trajanja_leta_minuti: 45,
    klasa: 'business',
    broj_preostalih_mesta: 10,
    cena: 415,
    tags: ['easyJat','London', 'Dubrovnik'],
    favorite: true,
    imageUrl: 'assets/5.jpg',
    stars: 3,
    status: "next",
    polazni_aerodrom: 'London Stansted',
    dolazni_aerodrom: 'Dubrovnik Airport'
  },
  {
    id:'12',
    avio_prevozinik: 'AirSerbia',
    polazna_lokacija: 'Belgrade',
    odredisna_lokacija: 'Nis',
    vreme_trajanja_leta_sati: 0,
    vreme_trajanja_leta_minuti: 30,
    klasa: 'business',
    broj_preostalih_mesta: 5,
    cena: 74,
    tags: ['AirSerbia','Nis', 'Belgrade'],
    favorite: false,
    imageUrl: 'assets/8.jpg',
    stars: 4,
    status: "cancelled",
    polazni_aerodrom: 'Nikola Tesla',
    dolazni_aerodrom: 'Konstantin Veliki'
  },
  {
    id:'2',
    avio_prevozinik: 'FlyDubai',
    polazna_lokacija: 'Dubai',
    odredisna_lokacija: 'Paris',
    vreme_trajanja_leta_sati: 5,
    vreme_trajanja_leta_minuti: 55,
    klasa: 'economy',
    broj_preostalih_mesta: 15,
    cena: 481,
    tags: ['FlyDubai','Dubai', 'Paris'],
    favorite: false,
    imageUrl: 'assets/1.jpg',
    stars: 4,
    status: "done",
    polazni_aerodrom: 'Dubai Airport',
    dolazni_aerodrom: 'Paris Charles de Gaulle Airport'
  },
  {
    id:'11',
    avio_prevozinik: 'AirSerbia',
    polazna_lokacija: 'Podgorica',
    odredisna_lokacija: 'Belgrade',
    vreme_trajanja_leta_sati: 1,
    vreme_trajanja_leta_minuti: 5,
    klasa: 'economy',
    broj_preostalih_mesta: 10,
    cena: 205,
    tags: ['AirSerbia','London', 'Belgrade'],
    favorite: true,
    imageUrl: 'assets/3.jpg',
    stars: 2,
    status: "next",
    polazni_aerodrom: 'Nikola Tesla',
    dolazni_aerodrom: 'Nikola Tesla'
  },
  {
    id:'9',
    avio_prevozinik: 'easyJat',
    polazna_lokacija: 'Dubrovnik',
    odredisna_lokacija: 'London',
    vreme_trajanja_leta_sati: 2,
    vreme_trajanja_leta_minuti: 50,
    klasa: 'business',
    broj_preostalih_mesta: 31,
    cena: 401,
    tags: ['easyJat','London', 'Dubrovnik'],
    favorite: true,
    imageUrl: 'assets/2.jpg',
    stars: 3,
    status: "cancelled",
    polazni_aerodrom: 'Dubrovnik Airport',
    dolazni_aerodrom: 'London Luton'
  },
  {
    id:'6',
    avio_prevozinik: 'Wizz',
    polazna_lokacija: 'London',
    odredisna_lokacija: 'Belgrade',
    vreme_trajanja_leta_sati: 2,
    vreme_trajanja_leta_minuti: 55,
    klasa: 'economy',
    broj_preostalih_mesta: 7,
    cena: 292,
    tags: ['Wizz','London', 'Belgrade'],
    favorite: false,
    imageUrl: 'assets/3.jpg',
    stars: 1,
    status: "next",
    polazni_aerodrom: 'London Luton',
    dolazni_aerodrom: 'Nikola Tesla'
  }
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 13},
  { name: 'Belgrade', count: 8},
  { name: 'Paris', count: 2},
  { name: 'Dubai', count: 2},
  { name: 'New York', count: 2},
  { name: 'London', count: 6},
  { name: 'Dubrovnik', count: 2},
  { name: 'Dublin', count: 2},
  { name: 'Nis', count: 1}
]
